version: "3"
services:
    database:
        container_name: dev-mysql
        image: mysql:8.0.23
        platform: linux/amd64
        volumes:
            - ./volumes/my.cnf:/etc/my.cnf
            - ./volumes/custom.cnf:/etc/mysql/conf.d/custom.cnf
            - my-datavolume:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=abacate1
            - MYSQL_DATABASE=manager
        ports:
            - "3306:3306"
volumes:
    my-datavolume: